import React, { useEffect, useState } from 'react';
import { ArrowLeft, LoaderCircle, UserPlus } from 'lucide-react';
import { User } from '../types';

export const RegistrationPage: React.FC<{ token: string; onAuthenticated: (user: User) => void }> = ({ token, onAuthenticated }) => {
  const [invitation, setInvitation] = useState<{ email: string; role: string } | null>(null);
  const [form, setForm] = useState({ name: '', username: '', password: '' });
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch(`/api/invitations/${encodeURIComponent(token)}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setInvitation(data.invitation); }).catch((reason) => setError(reason instanceof Error ? reason.message : 'Invitation unavailable.')); }, [token]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(`/api/invitations/${encodeURIComponent(token)}/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); history.replaceState({}, '', '/'); onAuthenticated(data.user); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Registration failed.'); } finally { setBusy(false); } };
  return <main className="flex min-h-[100dvh] items-center justify-center bg-[#08090c] p-4 text-zinc-100"><section className="w-full max-w-md rounded-[28px] border border-white/[.09] bg-[#121318] p-6 shadow-2xl sm:p-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-amber-300/20 bg-amber-300/[.07] text-amber-300"><UserPlus className="h-5 w-5" /></div><p className="mt-6 text-[10px] uppercase tracking-[.2em] text-amber-300">Workspace invitation</p><h1 className="mt-2 text-2xl font-semibold">Create your office account</h1>{invitation && <p className="mt-2 text-sm text-zinc-500">Invited as {invitation.role} · {invitation.email}</p>}<form onSubmit={submit} className="mt-7 space-y-3"><input required minLength={2} placeholder="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="w-full rounded-xl border border-white/[.09] bg-black/25 px-4 py-3 text-sm outline-none"/><input required minLength={3} placeholder="Username" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} className="w-full rounded-xl border border-white/[.09] bg-black/25 px-4 py-3 text-sm outline-none"/><input required minLength={10} type="password" placeholder="Password · at least 10 characters" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="w-full rounded-xl border border-white/[.09] bg-black/25 px-4 py-3 text-sm outline-none"/>{error && <p role="alert" className="rounded-xl border border-red-400/20 bg-red-400/[.07] px-3 py-2 text-xs text-red-300">{error}</p>}<button disabled={busy || !invitation} className="flex w-full items-center justify-center gap-2 rounded-xl bg-amber-300 py-3 text-sm font-semibold text-black disabled:opacity-40">{busy && <LoaderCircle className="h-4 w-4 animate-spin"/>}Join office</button></form><a href="/" className="mt-5 flex items-center justify-center gap-2 text-xs text-zinc-600 hover:text-zinc-300"><ArrowLeft className="h-3.5 w-3.5"/>Back to login</a></section></main>;
};
