import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, ImagePlus, LoaderCircle, Plus, Trash2, Type, Video, Volume2, VolumeX, X } from 'lucide-react';
import { useFloatingWindow, WindowResizeHandles } from '../hooks/useFloatingWindow';
import { getSocket } from '../lib/socket';
import { StoryContentType, StoryItem, User } from '../types';

interface Props { open: boolean; currentUser: User; onClose: () => void }
const defaultBounds = () => { const width = Math.min(900, window.innerWidth - 20); const height = Math.min(700, window.innerHeight - 24); return { x: Math.max(8, (window.innerWidth - width) / 2), y: Math.max(8, (window.innerHeight - height) / 2), width, height }; };
const readDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('File could not be read.')); reader.readAsDataURL(file); });
async function api(url: string, options?: RequestInit) { const response = await fetch(url, options); const data = response.status === 204 ? null : await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error || 'Story request failed.'); return data; }

export const StoriesWindow: React.FC<Props> = ({ open, currentUser, onClose }) => {
  const floating = useFloatingWindow({ initialBounds: defaultBounds, minWidth: 300, minHeight: 400 });
  const [stories, setStories] = useState<StoryItem[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [adding, setAdding] = useState(false);
  const [textStory, setTextStory] = useState('');
  const [caption, setCaption] = useState('');
  const [busy, setBusy] = useState(false);
  const [muted, setMuted] = useState(false);
  const [error, setError] = useState('');
  const imageInput = useRef<HTMLInputElement>(null);
  const videoInput = useRef<HTMLInputElement>(null);
  const load = async () => { const data = await api('/api/stories'); setStories(data.stories || []); setSelectedId((current) => current && data.stories.some((story: StoryItem) => story.id === current) ? current : data.stories[0]?.id || ''); };
  useEffect(() => { if (open) void load().catch((value) => setError(value.message)); }, [open]);
  useEffect(() => { if (!open) return; const socket = getSocket(); const refresh = () => void load(); socket.on('stories:updated', refresh); return () => { socket.off('stories:updated', refresh); }; }, [open]);
  const selected = stories.find((story) => story.id === selectedId);
  const people = useMemo(() => [...new Map(stories.map((story) => [story.userId, story.user])).values()], [stories]);
  const selectedIndex = Math.max(0, stories.findIndex((story) => story.id === selectedId));
  const move = (amount: number) => { if (!stories.length) return; setSelectedId(stories[(selectedIndex + amount + stories.length) % stories.length].id); };
  const add = async (contentType: StoryContentType, content: string) => { setBusy(true); setError(''); try { await api('/api/stories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contentType, content, caption }) }); setAdding(false); setTextStory(''); setCaption(''); await load(); } catch (value) { setError(value instanceof Error ? value.message : 'Story could not be added.'); } finally { setBusy(false); } };
  const addFile = async (file: File | undefined, type: 'image' | 'video') => { if (!file) return; const limit = type === 'image' ? 4 * 1024 * 1024 : 8 * 1024 * 1024; if (!file.type.startsWith(`${type}/`) || file.size > limit) { setError(`${type === 'image' ? 'Images' : 'Videos'} must be valid and smaller than ${type === 'image' ? 4 : 8} MB.`); return; } await add(type, await readDataUrl(file)); };
  const remove = async () => { if (!selected) return; setBusy(true); try { await api(`/api/stories/${selected.id}`, { method: 'DELETE' }); await load(); } catch (value) { setError(value instanceof Error ? value.message : 'Story could not be removed.'); } finally { setBusy(false); } };
  if (!open) return null;

  return <section role="dialog" aria-label="Stories" data-floating-window="stories" data-window-interacting={floating.interacting ? 'true' : 'false'} style={{ left: floating.bounds.x, top: floating.bounds.y, width: floating.bounds.width, height: floating.bounds.height }} className={`fixed z-[97] flex min-h-0 flex-col overflow-hidden rounded-[24px] border border-white/[.11] bg-black/98 shadow-[0_35px_120px_rgba(0,0,0,.84)] backdrop-blur-2xl ${floating.interacting ? '' : 'transition-[left,top,width,height] duration-150'}`}>
    <header data-window-drag-handle="true" onPointerDown={(event) => floating.startInteraction(event, 'drag')} className="flex h-14 shrink-0 touch-none cursor-move items-center gap-3 border-b border-white/[.08] px-4 active:cursor-grabbing"><div className="flex min-w-0 flex-1 gap-2 overflow-x-auto">{people.map((person) => <button key={person.id} onClick={() => setSelectedId(stories.find((story) => story.userId === person.id)?.id || '')} title={`${person.name}'s stories`} className={`shrink-0 rounded-full p-0.5 ${selected?.userId === person.id ? 'bg-gradient-to-br from-amber-300 via-pink-500 to-violet-500' : 'bg-zinc-700'}`}><img src={person.avatarUrl} alt={person.name} className="h-8 w-8 rounded-full border-2 border-black object-cover" /></button>)}</div><button onClick={() => setAdding((value) => !value)} aria-label="Add story" className="rounded-xl bg-white/[.07] p-2 text-zinc-300 hover:bg-white/[.12]"><Plus className="h-4 w-4" /></button><button onClick={onClose} aria-label="Close stories" className="p-2 text-zinc-500 hover:text-white"><X className="h-4 w-4" /></button></header>
    {adding && <div className="absolute right-3 top-16 z-30 w-[min(330px,calc(100%-1.5rem))] rounded-2xl border border-white/[.1] bg-[#18191e]/98 p-3 shadow-2xl"><div className="grid grid-cols-3 gap-2"><button onClick={() => imageInput.current?.click()} className="flex h-14 items-center justify-center rounded-xl border border-white/[.08] text-zinc-400 hover:text-white"><ImagePlus className="h-5 w-5" /></button><button onClick={() => videoInput.current?.click()} className="flex h-14 items-center justify-center rounded-xl border border-white/[.08] text-zinc-400 hover:text-white"><Video className="h-5 w-5" /></button><button onClick={() => setTextStory((value) => value || 'Share an update…')} className="flex h-14 items-center justify-center rounded-xl border border-white/[.08] text-zinc-400 hover:text-white"><Type className="h-5 w-5" /></button></div><input ref={imageInput} type="file" accept="image/*" className="hidden" onChange={(event) => { void addFile(event.target.files?.[0], 'image'); event.currentTarget.value = ''; }} /><input ref={videoInput} type="file" accept="video/*" className="hidden" onChange={(event) => { void addFile(event.target.files?.[0], 'video'); event.currentTarget.value = ''; }} />{textStory && <textarea autoFocus value={textStory} onChange={(event) => setTextStory(event.target.value)} maxLength={500} rows={4} className="mt-2 w-full resize-none rounded-xl border border-white/[.09] bg-black/30 p-3 text-sm outline-none" />}
      <input value={caption} onChange={(event) => setCaption(event.target.value)} maxLength={240} placeholder="Caption (optional)" className="mt-2 w-full rounded-xl border border-white/[.09] bg-black/30 px-3 py-2 text-xs outline-none" />{textStory && <button disabled={busy || !textStory.trim()} onClick={() => void add('text', textStory.trim())} className="mt-2 w-full rounded-xl bg-amber-300 py-2.5 text-xs font-semibold text-black">Share story</button>}{error && <p className="mt-2 text-[10px] text-red-300">{error}</p>}</div>}
    <div className="relative min-h-0 flex-1 overflow-hidden bg-[radial-gradient(circle_at_50%_30%,rgba(82,82,91,.25),transparent_45%)]">{busy && <LoaderCircle className="absolute left-4 top-4 z-20 h-4 w-4 animate-spin text-amber-300" />}{selected ? <>
      <div className="absolute left-4 right-4 top-3 z-20 flex gap-1">{stories.filter((story) => story.userId === selected.userId).map((story) => <span key={story.id} className={`h-0.5 flex-1 rounded-full ${story.id === selected.id ? 'bg-white' : 'bg-white/25'}`} />)}</div>
      <div className="absolute left-4 top-6 z-20 flex items-center gap-2"><img src={selected.user.avatarUrl} alt="" className="h-8 w-8 rounded-full object-cover" /><div><p className="text-xs font-semibold">{selected.user.name}</p><p className="text-[9px] text-zinc-500">{new Date(selected.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p></div></div>
      <div className="flex h-full items-center justify-center p-4 pt-14">{selected.contentType === 'image' && <img src={selected.content} alt={selected.caption} className="max-h-full max-w-full rounded-2xl object-contain" />}{selected.contentType === 'video' && <video key={selected.id} src={selected.content} autoPlay playsInline loop muted={muted} className="max-h-full max-w-full rounded-2xl object-contain" />}{selected.contentType === 'text' && <div className="flex aspect-[9/14] max-h-full w-full max-w-[430px] items-center justify-center rounded-[28px] bg-gradient-to-br from-violet-700 via-fuchsia-600 to-amber-500 p-9 text-center text-[clamp(1.5rem,4vw,3rem)] font-semibold leading-tight shadow-2xl">{selected.content}</div>}</div>
      {selected.caption && <p className="absolute bottom-5 left-1/2 z-20 max-w-[80%] -translate-x-1/2 rounded-xl bg-black/60 px-3 py-2 text-center text-xs backdrop-blur-lg">{selected.caption}</p>}
      <button onClick={() => move(-1)} aria-label="Previous story" className="absolute left-3 top-1/2 z-20 rounded-full bg-black/45 p-2 text-white"><ChevronLeft className="h-5 w-5" /></button><button onClick={() => move(1)} aria-label="Next story" className="absolute right-3 top-1/2 z-20 rounded-full bg-black/45 p-2 text-white"><ChevronRight className="h-5 w-5" /></button>
      {selected.contentType === 'video' && <button onClick={() => setMuted((value) => !value)} aria-label={muted ? 'Unmute story' : 'Mute story'} className="absolute right-14 top-5 z-20 rounded-full bg-black/50 p-2 text-white">{muted ? <VolumeX className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}</button>}{(selected.userId === currentUser.id || currentUser.isAdmin) && <button onClick={() => void remove()} aria-label="Delete story" className="absolute right-4 top-5 z-20 rounded-full bg-black/50 p-2 text-zinc-300 hover:text-red-300"><Trash2 className="h-4 w-4" /></button>}
    </> : <div className="flex h-full flex-col items-center justify-center text-center"><span className="flex h-16 w-16 items-center justify-center rounded-full border border-dashed border-white/15 text-zinc-600"><Plus className="h-6 w-6" /></span><h2 className="mt-4 text-sm font-semibold">No active stories</h2><p className="mt-1 text-[10px] text-zinc-600">Share an image, short video, or daily update.</p><button onClick={() => setAdding(true)} className="mt-4 rounded-xl bg-white/[.07] px-4 py-2 text-xs">Add story</button></div>}</div>
    <WindowResizeHandles onResizeStart={(event, direction) => floating.startInteraction(event, 'resize', direction)} />
  </section>;
};
